### PR TITLE
Update Settings.osl

### PR DESCRIPTION
**Pull request by MiloDev123**

### CODE REVIEW

**Comment by ThePandaDever** [comment]
cringe

**Comment by ThePandaDever** [comment]
bros only doing it for the badge 😭

**Comment by MiloDev123** [comment]
> bros only doing it for the badge 😭

for the 2nd time @ThePandaDever

**Comment by MiloDev123** [comment]
btw thanks for the badge @ThePandaDever (the one of having many comments in a pr)

**Comment by ThePandaDever** [comment]
ur litterally a carbon based organism shut it

**Comment by MiloDev123** [comment]
like you

**Comment by ThePandaDever** [comment]
> like you

nuh uh

**Comment by MiloDev123** [comment]
> > like you
> 
> nuh uh

yuh uh

**Comment by MiloDev123** [comment]
bro doesnt have words 💀

**Comment by ThePandaDever** [comment]
because i honestly couldnt give 2 singular shits 😱
aspecially on a pr which mist has litterally already said is useless and doesnt need to be added

**Comment by MiloDev123** [comment]
Well, if it doesn't need to be added and Mist already called it useless, why waste two perfectly good shits on it? My indifference is just eco-friendly like that. 🌍💁‍♂️

**Pull request merged**
